site_name: 发烧的客体-Tutorial-Wiki
nav:
  - Home : index.md
  - Programming:
      - Python:
          - Python基础:
                - 词法分析: Programming/Python/Python基础/词法分析.md
          - Python进阶:
                - 进阶: Programming/Python/Python高级/Python高级.md
          - Python高级:
                - 高级: Programming/Python/Python进阶/Python进阶.md
          - Python标准与常用库:
                - 标准与常用: Programming/Python/Python标准与常用库/Python标准库.md
      - Go: Programming/Go/Go.md
      - Rust: Programming/Rust/Rust.md
      - C: Programming/C/C.md
      - Cpp: Programming/Cpp/Cpp.md
      - Csharp: Programming/Csharp/Csharp.md
      - JavaScript: Programming/JavaScript/JavaScript.md
      - Java: Programming/Java/Java.md
      - TypeScript: Programming/TypeScript/TypeScript.md
      - Bash: Programming/Bash/Bash.md
      - CSS3: Programming/CSS3/CSS3.md
      - HTML5: Programming/HTML5/HTML5.md
      - Nodejs: Programming/Nodejs/Nodejs.md
      - PowerShell: Programming/PowerShell/PowerShell.md
  - Tutorial:
      - Python:
          - mkdocs-material: Tutorial/python/mkdocs-material.md
          - scipy: Tutorial/python/scipy.md
          - Matplotlib: Tutorial/python/Matplotlib.md
          - pyautogui: Tutorial/python/pyautogui.md
          - Pandas: Tutorial/python/Pandas.md
          - numpy: Tutorial/python/numpy.md
          - PyQT: Tutorial/python/PyQT.md
          - Pyinstaller: Tutorial/python/Pyinstaller.md
      - Open:
          - OpenGL: Tutorial/Open/OpenGL.md
          - OpenCV: Tutorial/Open/OpenCV.md
      - Auto:
          - Autoit: Tutorial/Auto/Autoit.md
      - Science:
          - MATLAB: Tutorial/science/MATLAB.md
      - GUI:
          - QT: Tutorial/GUI/QT.md
          - QML: Tutorial/GUI/QML.md
          - WPF: Tutorial/GUI/WPF.md
          - MFC: Tutorial/GUI/MFC.md
  - Tools:
      - Git: tools/Git.md
      - Sigil: tools/Sigil.md
      - "CMake Cookbook": tools/CMake_Cookbook.md
  - Reference:
      - 编辑器:
          - vscode:
              - vscode配置clang: Reference/编辑器/vscode/vscode配置clang.md
      - 文章:
          - 人工智能:
              - open系列库: Reference/文章/人工智能/open系列库.md
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs # 上方
#    - toc.integrate
    - navigation.prune # 自动隐藏导航栏