site_name: 发烧的客体-Tutorial-Wiki
site_url: https://abottleofmilk.github.io/Tutorial-wiki/
nav:
  - Home: index.md
  - Programming:
      - Python:
          - Python教程:
              - 类: Programming\Python\Python 教程\类.md
              - 虚拟环境和包: Programming\Python\Python 教程\虚拟环境和包.md
          - Python高级:
              - 高级: Programming\Python\Python高级\Python进阶.md
          - Python标准与常用库:
              - 标准与常用: Programming\Python\Python标准与常用库\Python标准库.md
          - Python官方文档:
              - 术语对照表: Programming\Python\Python官方文档\术语对照表.md
      - Go: Programming\Go\Go.md
      - Rust: Programming\Rust\Rust.md
      - C: Programming\C\C.md
      - Cpp: Programming\Cpp\Cpp.md
      - Csharp:
          - 图解C#:
              - 异步编程: Programming\Csharp\图解C#\异步编程.md #   Programming\Cpp\Cpp基础\Cpp异常.md
                # - Programming\Cpp\Cpp基础\Cpp继承与派生.md
                # - Programming\Csharp\Csharp.md
                # - Programming\Csharp\Net Core\依赖注入.md
              - C#和.NET Core: Programming\Csharp\图解C#\C#和.NET Core.md
              - C#编程概述: Programming\Csharp\图解C#\C#编程概述.md
              - C#编程概述: Programming\Csharp\图解C#\LINQ.md
              - 事件: Programming\Csharp\图解C#\事件.md
              - 其他主题: Programming\Csharp\图解C#\其他主题.md
              - 反射和特性: Programming\Csharp\图解C#\反射和特性.md
              - 命名空间和程序集: Programming\Csharp\图解C#\命名空间和程序集.md
              - 委托: Programming\Csharp\图解C#\委托.md
              - 异常: Programming\Csharp\图解C#\异常.md
              - 接口: Programming\Csharp\图解C#\接口.md
              - 数组: Programming\Csharp\图解C#\数组.md
              - 新增特性: Programming\Csharp\图解C#\新增特性.md
              - 枚举: Programming\Csharp\图解C#\枚举.md
              - 枚举器和迭代器: Programming\Csharp\图解C#\枚举器和迭代器.md
              - 泛型: Programming\Csharp\图解C#\泛型.md
              - 深入理解类: Programming\Csharp\图解C#\深入理解类.md
              - 类和继承: Programming\Csharp\图解C#\类和继承.md
              - 类型、存储和变量: Programming\Csharp\图解C#\类型、存储和变量.md
              - 类的基本概念: Programming\Csharp\图解C#\类的基本概念.md
              - 结构: Programming\Csharp\图解C#\结构.md
              - 语句: Programming\Csharp\图解C#\语句.md
              - 转换: Programming\Csharp\图解C#\转换.md
              - 预处理指令: Programming\Csharp\图解C#\预处理指令.md
      - JavaScript: Programming\JavaScript\JavaScript.md
      - Java: Programming\Java\Java.md
      - TypeScript: Programming\TypeScript\TypeScript.md
      - Bash: Programming\Bash\Bash.md
      - CSS3: Programming\CSS3\CSS3.md
      - HTML5: Programming\HTML5\HTML5.md
      - Nodejs: Programming\Nodejs\Nodejs.md
      - PowerShell: Programming\PowerShell\PowerShell.md
  - Tutorial:
      - "front-end":
          - Vue: Tutorial\front-end\vue\Vue基础.md
          - React: Tutorial\front-end\react\React基础.md
      - Python:
          - mkdocs-material:
              - 颜色: Tutorial\python\mkdocs\mkdocs-material.md
          - scipy: Tutorial\python\scipy.md
          - Matplotlib:
              - 快速指南: Tutorial\python\Matplotlib\快速指南.md
              - 编码风格: Tutorial\python\Matplotlib\编码风格.md
              - 交互figures: Tutorial\python\Matplotlib\说明\交互figures.md
              - 后端: Tutorial\python\Matplotlib\说明\后端.md
          - pyautogui: Tutorial\python\pyautogui.md
          - Pandas: Tutorial\python\Pandas.md
          - numpy: Tutorial\python\numpy.md
          - PyQT:
              - "Python Qt GUI与数据可视化编程":
                  - 数据可视化:
                      - PyQtChart二维绘图: Tutorial\python\PyQt\Python Qt GUI与数据可视化编程\PyQtChart二维绘图.md
                      - PyQtDataVisualization三维绘图: Tutorial\python\PyQt\Python Qt GUI与数据可视化编程\PyQtDataVisualization三维绘图.md
                      - Matplotlib数据可视化: Tutorial\python\PyQt\Python Qt GUI与数据可视化编程\Matplotlib数据可视化.md
                      - 事件处理: Tutorial\python\PyQt\Python Qt GUI与数据可视化编程\事件处理.md
          - Pyinstaller: Tutorial\python\Pyinstaller.md
      - Open:
          - OpenGL: Tutorial\Open\OpenGL.md
          - OpenCV:
              - OpenCV轻松入门-面向Python:
                  - OpenCV入门: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\OpenCV入门.md
                  - 图像处理基础: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\图像处理基础.md
                  - 图像运算: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\图像运算.md
                  - 色彩空间类型转换: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\色彩空间类型转换.md
                  - 几何变换: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\几何变换.md
                  - 阈值处理: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\阈值处理.md
                  - 图像平滑处理: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\图像平滑处理.md
                  - 形态学操作: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\形态学操作.md
                  - 图像梯度: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\图像梯度.md
                  - Canny边缘探测: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\Canny边缘探测.md
                  - 图像金字塔: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\图像金字塔.md
                  - 图像轮廓: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\图像轮廓.md
                  - 直方图处理: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\直方图处理.md
                  - 傅里叶变换: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\傅里叶变换.md
                  - 模板匹配: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\模板匹配.md
                  - 霍夫变换: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\霍夫变换.md
                  - 图像分隔与提取: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\图像分隔与提取.md
                  - 视频处理: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\支持向量机.md
                  - 绘图及交互: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\绘图及交互.md
                  - K近邻算法: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\K近邻算法.md
                  - 支持向量机: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\支持向量机.md
                  - K均值聚类: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\K均值聚类.md
                  - 人脸识别: Tutorial\Open\OpenCV\OpenCV轻松入门-面向Python\人脸识别.md
      - Auto:
          - Autoit: Tutorial\Auto\Autoit.md
      - Science:
          - MATLAB: Tutorial\science\MATLAB.md
      - GUI:
          - QT:
              - Qt5.9C++开发指南:
                  - Qt基础: Tutorial\GUI\Qt\Qt5.9C++开发指南\Qt.md
                  - 布局管理: Tutorial\GUI\Qt\Qt5.9C++开发指南\布局管理.md
                  - 对话框: Tutorial\GUI\Qt\Qt5.9C++开发指南\对话框.md
                  - 工具: Tutorial\GUI\Qt\Qt5.9C++开发指南\工具.md
                  - 多媒体: Tutorial\GUI\Qt\Qt5.9C++开发指南\多媒体.md
                  - 绘图: Tutorial\GUI\Qt\Qt5.9C++开发指南\绘图.md
                  - 项: Tutorial\GUI\Qt\Qt5.9C++开发指南\项.md
                  - 应用程序设计辅助功能: Tutorial\GUI\Qt\Qt5.9C++开发指南\应用程序设计辅助功能.md
                  - 数据库: Tutorial\GUI\Qt\Qt5.9C++开发指南\数据库.md
                  - 窗口: Tutorial\GUI\Qt\Qt5.9C++开发指南\窗口.md
                  - 网络编程: Tutorial\GUI\Qt\Qt5.9C++开发指南\网络编程.md
                  - 事件与信号: Tutorial\GUI\Qt\Qt5.9C++开发指南\事件与信号.md
                  - 文件: Tutorial\GUI\Qt\Qt5.9C++开发指南\文件.md
                  - "Model&View": Tutorial\GUI\Qt\Qt5.9C++开发指南\Model&View.md
                  - "QML 和 QtQuick 2": Tutorial\GUI\Qt\Qt5.9C++开发指南\QML 和 QtQuick 2.md
          - QML: Tutorial\GUI\QML.md
          - WPF: Tutorial\GUI\WPF.md
          - MFC: Tutorial\GUI\MFC.md
  - Tools:
      - Git: tools\Git.md
      - Sigil: tools\Sigil.md
      - "CMake Cookbook": tools\CMake_Cookbook.md
      - "Vim": tools\vim.md
      - "资源整合": tools\资源网.md
  - Reference:
      - 编辑器:
          - vscode:
              - vscode配置clang: Reference\编辑器\vscode\vscode配置clang.md
      - 文章:
          - 人工智能:
              - open系列库: Reference\文章\人工智能\open系列库.md
  - Embedded:
      - Arduino: Tutorial\Embedded\Arduino\Arduino.md
  - Languages: 
      - English: 
        - 100句子记完7000雅思单词: languages\english\100句子记完7000雅思单词\01-25.md
  - Other:
      - reading:
          - 七周七语言: Other\reading\七周七语言.md
  - Tags: tags.md
theme:
  name: material
  #   search_index_only: false
  icon:
    tag:
      CSS3: simple/css3
      Python: simple/python
      default: material/robot-happy
      document: material/file-document
      Qt: simple/qt
  palette:
    # Palette toggle for light mode
    # - accent: deep orange    # primary: deep purple
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      accent: deep orange
    #   primary: green
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      accent: deep orange
  features:
    - navigation.tracking # 启用锚点跟踪后，地址栏中的 URL 会自动更新为目录中突出显示的活动锚点。
    - navigation.top # 当用户在向下滚动后再次开始向上滚动时，可以显示返回顶部按钮。
    # - navigation.tabs.sticky
    - navigation.tabs # 上方显示顶级导航
    - navigation.sections # 分组显示 平铺
    - toc.follow # 侧边栏跟随导航条
    # - navigation.indexes
    # - toc.integrate 自动展开
    - navigation.prune # 自动隐藏导航栏
    - search.highlight # 搜索内容匹配高亮
    - search.share #  当用户单击共享按钮时，URL 会自动复制到剪贴板。
    - search.suggest # 搜索建议
    - content.code.annotate
plugins:
  - tags:
      tags_file: tags.md
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        - ja
extra:
  tags:
    CSS3: CSS3
    Python: Python
    Document: document
    Qt: Qt
#   version:
#     provider: mike
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js